version: "3"

services:
  app:
    build: .
    container_name: nuxt-blog
    ports: ["3000:3000"]
    volumes: [".:/data/app"]
    environment:
      - HOST=0.0.0.0
    working_dir: /data/app
    command: ./entrypoint.sh
